version: '3.0'
services:
  tscns:
    image: crs4/tscns:latest
    ports:
      - 443:443
    environment:
      - TZ=CET
      - DEVELOPMENT=true
      - SSL=true
      - SERVER_NAME=tscns
      - HGW_FRONTEND_ADDR=hgwfrontend:8000
      - CONSENT_MANAGER_ADDR=consentmanager:8002
    volumes:
      - ../../../hgw_frontend/saml2/metadata.xml:/root/metadata/hgw-frontend-metadata.xml
      - ../../../consent_manager/saml2/metadata.xml:/root/metadata/consent-manager-metadata.xml
      - ../../../certs/ca/web/certs/ca/web.chain.cert.pem:/root/certificates/ca_certs/ca-development.crt
      - ../../../certs/ca/web/certs/tscns/idp_server.cert.pem:/root/certificates/idp_server.cert.pem
      - ../../../certs/ca/web/certs/tscns/idp_server.key.pem:/root/certificates/idp_server.key.pem
      - ../../../certs/ca/web/certs/tscns/idp-backchannel.crt:/opt/shibboleth-idp/credentials/idp-backchannel.crt
      - ../../../certs/ca/web/certs/tscns/idp-backchannel.p12:/opt/shibboleth-idp/credentials/idp-backchannel.p12
      - ../../../certs/ca/web/certs/tscns/idp-signing.crt:/opt/shibboleth-idp/credentials/idp-signing.crt
      - ../../../certs/ca/web/certs/tscns/idp-signing.key:/opt/shibboleth-idp/credentials/idp-signing.key
      - ../../../certs/ca/web/certs/tscns/idp-encryption.crt:/opt/shibboleth-idp/credentials/idp-encryption.crt
      - ../../../certs/ca/web/certs/tscns/idp-encryption.key:/opt/shibboleth-idp/credentials/idp-encryption.key

  hgw_frontend:
    image: crs4/hgw_frontend:latest
    environment:
      - HTTP_PORT=8000
      - DJANGO_APP_NAME=hgw_frontend
    ports:
      - 8000:8000
    volumes:
      - ../../../hgw_frontend/:/container/devservice/
      - ../../../hgw_common/hgw_common/:/container/devservice/hgw_common/
      - ./config_files/hgw_frontend_config.tscns.yml:/etc/hgw_service/hgw_frontend_config.yml
      - ../../../certs/ca/root/ca.cert.pem:/cacerts/ca.cert.pem
      - ../../../certs/ca/web/certs/ca/web.cert.pem:/cacerts/web.cert.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.cert.pem:/cacerts/kafka.cert.pem
      - ../../../certs/ca/web/certs/hgwfrontend:/container/web_certs/
      - ../../../certs/ca/kafka/certs/hgwfrontend/cert.pem:/container/client_certs/cert.pem
      - ../../../certs/ca/kafka/certs/hgwfrontend/key.pem:/container/client_certs/key.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.chain.cert.pem:/container/client_certs/kafka.chain.cert.pem
    networks:
      default:
        aliases:
          - hgwfrontend

  hgw_backend:
    image: crs4/hgw_backend:latest
    depends_on:
      - kafka
    entrypoint: ["/custom_entrypoint/wait-for-it.sh", "kafka:9093", "--", "/docker-entrypoint.sh"]
    environment:
      - HTTP_PORT=8003
      - DJANGO_APP_NAME=hgw_backend
      - TZ=CET
    ports:
      - 8003:8003
    volumes:
      - ../../../hgw_backend/:/container/devservice/
      - ../../../hgw_common/hgw_common/:/container/devservice/hgw_common/
      - ./config_files/hgw_backend_config.yml:/etc/hgw_service/hgw_backend_config.yml
      - ../../../certs/ca/root/ca.cert.pem:/cacerts/ca.cert.pem
      - ../../../certs/ca/web/certs/ca/web.cert.pem:/cacerts/web.cert.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.cert.pem:/cacerts/kafka.cert.pem
      - ../../../certs/ca/web/certs/hgwbackend/:/container/web_certs/
      - ../../../certs/ca/kafka/certs/hgwbackend/cert.pem:/container/client_certs/cert.pem
      - ../../../certs/ca/kafka/certs/hgwbackend/key.pem:/container/client_certs/key.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.chain.cert.pem:/container/client_certs/kafka.chain.cert.pem
      - ../../../certs/ca/web/certs/hgwbackend/source_endpoint_mockup_client.cert.pem:/container/devservice/media/source_endpoint_mockup_client.cert.pem
      - ../../../certs/ca/web/certs/hgwbackend/source_endpoint_mockup_client.key.pem:/container/devservice/media/source_endpoint_mockup_client.key.pem
    networks:
      default:
        aliases:
          - hgwbackend

  consent_manager:
    image: crs4/consent_manager:latest
    environment:
      - HTTP_PORT=8002
      - DJANGO_APP_NAME=consent_manager
      - TZ=CET
    ports:
      - 8002:8002
    volumes:
      - ../../../consent_manager/:/container/devservice/
      - ../../../hgw_common/hgw_common/:/container/devservice/hgw_common/
      - ./config_files/consent_manager_config.tscns.yml:/etc/hgw_service/consent_manager_config.yml
      - ../../../certs/ca/root/ca.cert.pem:/cacerts/ca.cert.pem
      - ../../../certs/ca/web/certs/ca/web.cert.pem:/cacerts/web.cert.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.cert.pem:/cacerts/kafka.cert.pem
      - ../../../certs/ca/web/certs/consentmanager/:/container/web_certs/
    networks:
      default:
        aliases:
          - consentmanager

  kafka:
    image: crs4/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_PORT=9092
      - KAFKA_SSL_PORT=9093
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - TZ=CET
    extra_hosts:
      - "kafka:127.0.1.1"
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ../../../certs/ca/kafka/certs/kafka-server/:/container/certs/
    networks:
      default:
        aliases:
          - kafka

  hgw_dispatcher:
    image: crs4/hgw_dispatcher:latest
    depends_on:
      - kafka
      - consent_manager
      - hgw_frontend
      - hgw_backend
    entrypoint: ["/custom_entrypoint/wait-for-it.sh", "kafka:9093", "--",
                 "/custom_entrypoint/wait-for-it.sh", "hgw_frontend:8000", "--",
                 "/custom_entrypoint/wait-for-it.sh", "consent_manager:8002", "--",
                 "/custom_entrypoint/wait-for-it.sh", "hgw_backend:8003", "--", "/docker-entrypoint.sh"]
    volumes:
      - ../../../hgw_dispatcher/:/container/devservice
      - ../../../hgw_common/hgw_common/:/container/devservice/hgw_common/
      - ./config_files/hgw_dispatcher_config.yml:/etc/hgw_service/hgw_dispatcher_config.yml
      - ../../../certs/ca/root/ca.cert.pem:/cacerts/ca.cert.pem
      - ../../../certs/ca/web/certs/ca/web.cert.pem:/cacerts/web.cert.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.cert.pem:/cacerts/kafka.cert.pem
      - ../../../certs/ca/kafka/certs/hgwdispatcher/cert.pem:/container/client_certs/cert.pem
      - ../../../certs/ca/kafka/certs/hgwdispatcher/key.pem:/container/client_certs/key.pem
      - ../../../certs/ca/kafka/certs/ca/kafka.chain.cert.pem:/container/client_certs/kafka.chain.cert.pem